# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build sample-node-ts`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t sample-node-ts`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system sample-node-ts && \
          adduser --system -G sample-node-ts sample-node-ts

COPY dist/sample-node-ts sample-node-ts/
RUN chown -R sample-node-ts:sample-node-ts .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix sample-node-ts --omit=dev -f install

CMD [ "node", "sample-node-ts" ]
